server:
  port: 8085

spring:
  application:
    name: delivery-service

  datasource:
    url: jdbc:postgresql://localhost:5432/nearkart_delivery
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: delivery-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

nearkart:
  delivery:
    max-auto-assign-radius-km: 5
    otp-expiry-minutes: 10

kafka:
  topics:
    order-ready-for-pickup: order.ready-for-pickup
    delivery-assigned: delivery.assigned
    delivery-status-changed: delivery.status-changed

logging:
  level:
    in.nearkart.delivery: DEBUG
