package in.nearkart.notification.entity;

public enum NotificationType {
    ORDER_PLACED,
    ORDER_CONFIRMED,
    ORDER_PREPARING,
    ORDER_READY_FOR_PICKUP,
    ORDER_PICKED_UP,
    ORDER_OUT_FOR_DELIVERY,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    REFUND_INITIATED,
    REFUND_SUCCESS,
    WALLET_CREDITED,
    WALLET_DEBITED,
    PROMOTIONAL
}
