server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nearkart
    username: postgres
    password: Bharath@2004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    enabled: false

nearkart:
  jwt:
    secret: NearKartSuperSecretKey2026SecureString!!
    access-token-expiry-ms: 900000
    refresh-token-expiry-ms: 604800000
  otp:
    expiry-minutes: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    in.nearkart: DEBUG
    org.springframework.security: INFO
