server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/nearkart}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:changeme}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET:TmVhcktBUlRTdXBlclNlY3JldEtleTIwMjZTZWN1cmVTdHJpbmc=}
  expiry-ms: 900000
  refresh-token-expiry: 604800000

app:
  otp:
    expiry-minutes: 5
    length: 6

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.nearkart: DEBUG
    org.springframework.security: INFO
