server:
  port: 8085

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nearkart_inventory
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:bXlTdXBlclNlY3JldEtleUZvck5lYXJLYXJ0QXBwbGljYXRpb24xMjM0NTY=}

kafka:
  topic:
    inventory-low-stock: inventory-low-stock
    inventory-out-of-stock: inventory-out-of-stock

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.nearkart.inventoryservice: DEBUG
