server:
  port: 8087

spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nearkart_admin
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:yourpassword}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:bXlTdXBlclNlY3JldEtleUZvck5lYXJLYXJ0QXBwbGljYXRpb24xMjM0NTY=}

logging:
  level:
    com.nearkart.admin: DEBUG
