apiVersion: v1
kind: ConfigMap
metadata:
  name: nearkart-config
  namespace: nearkart
data:
  SPRING_PROFILES_ACTIVE: "prod"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
